{
  lib,
  pkgs,
  config,
  ...
}:
let
  cfg = config.media-server.beszel;
in
{
  options.media-server.beszel = {
    enable = lib.mkEnableOption "Beszel monitoring hub and agent";

    adminEmail = lib.mkOption {
      type = lib.types.str;
      default = "ruddickmg@gmail.com";
      description = "Email address for the Beszel admin account. Only used on first setup.";
    };

    adminPassword = lib.mkOption {
      type = lib.types.str;
      default = "admin";
      description = "Password for the Beszel admin account. Only used on first setup. Tailscale is the access control layer.";
    };
  };

  config = lib.mkIf cfg.enable {
    # Beszel hub — PocketBase-backed web dashboard
    services.beszel.hub = {
      enable = true;
      host = "127.0.0.1";
      port = 8090;
      # Beszel migration auto-creates user + superuser on first start:
      # BESZEL_HUB_USER_EMAIL fallback: USER_EMAIL -> temp admin (_@b.b)
      # BESZEL_HUB_USER_PASSWORD fallback: USER_PASSWORD -> random password
      # When both are set, it also creates a regular user (admin role, verified).
      environment = {
        BESZEL_HUB_USER_EMAIL = cfg.adminEmail;
        BESZEL_HUB_USER_PASSWORD = cfg.adminPassword;
      };
    };

    # Beszel agent — runs on the same host, hub connects via SSH
    services.beszel.agent = {
      enable = true;
      openFirewall = false;
      environment = {
        PORT = "45876";
      };
      environmentFile = "/var/lib/beszel-agent/env";
    };

    # Ensure podman docker socket is available so the agent can read container stats
    virtualisation.podman.dockerSocket.enable = lib.mkDefault true;

    # Create directories for agent env file and hub data
    systemd.tmpfiles.rules = [
      "d /var/lib/beszel-agent 0750 root beszel-agent -"
      "d /var/lib/beszel-hub 0750 beszel-hub beszel-hub -"
    ];

    # Reads the hub's SSH key from disk and writes it to the agent env file,
    # then registers the local agent as a system in the hub via API.
    # The hub generates its SSH key at /var/lib/beszel-hub/beszel_data/id_ed25519
    # on first startup (via GetSSHKey in beszel/internal/hub/hub.go).
    # The agent is skipped on first boot by ConditionPathExists; this service
    # writes the key and restarts the agent so it picks it up.
    systemd.services.beszel-init = {
      description = "Configure Beszel agent and register system with hub";
      after = [ "beszel-hub.service" ];
      wants = [ "beszel-hub.service" ];
      wantedBy = [ "multi-user.target" ];
      environment = {
        ADMIN_EMAIL = cfg.adminEmail;
        ADMIN_PASSWORD = cfg.adminPassword;
      };
      unitConfig = {
        OnFailure = "notify-gotify@%n.service";
      };
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      path = [
        pkgs.openssh
        pkgs.coreutils
        pkgs.curl
        pkgs.jq
      ];
      script = ''
        SSH_KEY="/var/lib/beszel-hub/beszel_data/id_ed25519"
        AGENT_ENV="/var/lib/beszel-agent/env"
        HUB_API="http://127.0.0.1:8090"

        # Wait for hub to generate SSH key
        for i in $(seq 1 60); do
          if [ -f "$SSH_KEY" ]; then
            break
          fi
          sleep 1
        done

        if [ ! -f "$SSH_KEY" ]; then
          echo "ERROR: Hub SSH key not found at $SSH_KEY after 60s" >&2
          exit 1
        fi

        # Extract public key from hub's private key
        HUB_KEY=$(ssh-keygen -y -f "$SSH_KEY" 2>/dev/null)

        if [ -z "$HUB_KEY" ]; then
          echo "ERROR: Failed to read hub SSH key" >&2
          exit 1
        fi

        # Write env file if key changed
        CURRENT_KEY=""
        if [ -s "$AGENT_ENV" ]; then
          CURRENT_KEY=$(grep "^KEY=" "$AGENT_ENV" | cut -d'=' -f2-)
        fi

        if [ "$CURRENT_KEY" != "$HUB_KEY" ]; then
          echo "Updating agent environment file..."
          printf '%s\n' \
            '# Beszel agent configuration' \
            '# Auto-generated by beszel-init.service' \
            'PORT=45876' \
            "KEY=$HUB_KEY" \
            > "$AGENT_ENV"

          chown root:beszel-agent "$AGENT_ENV"
          chmod 640 "$AGENT_ENV"

          systemctl restart beszel-agent.service
        else
          echo "Agent key already up to date"
        fi

        # Wait for hub API to be ready
        for i in $(seq 1 30); do
          if curl -sf "$HUB_API/api/" >/dev/null 2>&1; then
            break
          fi
          sleep 1
        done

        # Authenticate as admin user (retry — migration may still be creating the user)
        for i in $(seq 1 30); do
          AUTH_RESPONSE=$(curl -sf "$HUB_API/api/collections/users/auth-with-password" \
            -H "Content-Type: application/json" \
            -d "$(jq -nc --arg identity "$ADMIN_EMAIL" --arg password "$ADMIN_PASSWORD" '{identity:$identity,password:$password}')" 2>/dev/null) && break
          sleep 1
        done

        ADMIN_TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.token // empty')
        ADMIN_ID=$(echo "$AUTH_RESPONSE" | jq -r '.record.id // empty')

        if [ -z "$ADMIN_TOKEN" ]; then
          echo "WARNING: Could not authenticate with hub — system not registered. Add it manually in the dashboard." >&2
          exit 0
        fi

        # Check if system already exists
        EXISTING=$(curl -sf "$HUB_API/api/collections/systems/records" \
          --get --data-urlencode 'filter=name="media-server"' \
          -H "Authorization: Bearer $ADMIN_TOKEN" 2>/dev/null | jq -r '.items[0].id // empty')

        if [ -n "$EXISTING" ]; then
          echo "System 'media-server' already registered (id: $EXISTING)"
        else
          echo "Registering 'media-server' system with hub..."
          CREATE_RESPONSE=$(curl -sf -X POST "$HUB_API/api/collections/systems/records" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $ADMIN_TOKEN" \
            -d "$(printf '{"name":"media-server","host":"127.0.0.1","port":45876,"users":["%s"]}' "$ADMIN_ID")" 2>/dev/null)
          if [ $? -eq 0 ]; then
            echo "System registered successfully"
          else
            echo "WARNING: Failed to create system in hub — add it manually in the dashboard." >&2
          fi
        fi
      '';
    };

    # Override upstream ExecStartPre: beszel 0.18.7 doesn't have the history-sync
    # subcommand, causing a non-fatal error in the logs.
    systemd.services.beszel-hub.serviceConfig.ExecStartPre = lib.mkForce [
      "${config.services.beszel.hub.package}/bin/beszel-hub migrate up"
    ];

    # Skip agent start until init writes the env file (first boot).
    # OnFailure notifications are independent of ordering to avoid cycles.
    systemd.services.beszel-agent = {
      unitConfig = {
        ConditionPathExists = "/var/lib/beszel-agent/env";
        OnFailure = "notify-gotify@%n.service";
      };
    };
  };
}
