{
  lib,
  pkgs,
  config,
  ...
}:
let
  cfg = config.media-server.beszel;
in
{
  options.media-server.beszel = {
    enable = lib.mkEnableOption "Beszel monitoring hub and agent";

    adminEmail = lib.mkOption {
      type = lib.types.str;
      default = "ruddickmg@gmail.com";
      description = "Email address for the Beszel admin account. Only used on first setup.";
    };

    adminPassword = lib.mkOption {
      type = lib.types.str;
      default = "admin";
      description = "Password for the Beszel admin account. Only used on first setup. Tailscale is the access control layer.";
    };
  };

  config = lib.mkIf cfg.enable {
    # Beszel hub — PocketBase-backed web dashboard
    services.beszel.hub = {
      enable = true;
      host = "127.0.0.1";
      port = 8090;
      # Beszel migration auto-creates user + superuser on first start:
      # BESZEL_HUB_USER_EMAIL fallback: USER_EMAIL -> temp admin (_@b.b)
      # BESZEL_HUB_USER_PASSWORD fallback: USER_PASSWORD -> random password
      # When both are set, it also creates a regular user (admin role, verified).
      environment = {
        BESZEL_HUB_USER_EMAIL = cfg.adminEmail;
        BESZEL_HUB_USER_PASSWORD = cfg.adminPassword;
      };
    };

    # Beszel agent — runs on the same host, hub connects via SSH
    services.beszel.agent = {
      enable = true;
      openFirewall = false;
      environment = {
        PORT = "45876";
      };
      environmentFile = "/var/lib/beszel-agent/env";
    };

    # Ensure podman docker socket is available so the agent can read container stats
    virtualisation.podman.dockerSocket.enable = lib.mkDefault true;

    # Create directories for agent env file and hub data
    systemd.tmpfiles.rules = [
      "d /var/lib/beszel-agent 0750 root beszel-agent -"
      "d /var/lib/beszel-hub 0750 beszel-hub beszel-hub -"
    ];

    # Reads the hub's SSH key from disk and writes it to the agent env file.
    # No API calls — avoids auth tokens, DB state corruption, and ordering cycles.
    # The hub generates its SSH key at /var/lib/beszel-hub/beszel_data/id_ed25519
    # on first startup (via GetSSHKey in beszel/internal/hub/hub.go).
    # The agent is skipped on first boot by ConditionPathExists; this service
    # writes the key and restarts the agent so it picks it up.
    systemd.services.beszel-init = {
      description = "Configure Beszel agent with hub SSH key";
      after = [ "beszel-hub.service" ];
      wants = [ "beszel-hub.service" ];
      wantedBy = [ "multi-user.target" ];
      unitConfig = {
        OnFailure = "notify-gotify@%n.service";
      };
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      path = [
        pkgs.openssh
        pkgs.coreutils
      ];
      script = ''
        SSH_KEY="/var/lib/beszel-hub/beszel_data/id_ed25519"
        AGENT_ENV="/var/lib/beszel-agent/env"

        # Wait for hub to generate SSH key
        for i in $(seq 1 60); do
          if [ -f "$SSH_KEY" ]; then
            break
          fi
          sleep 1
        done

        if [ ! -f "$SSH_KEY" ]; then
          echo "ERROR: Hub SSH key not found at $SSH_KEY after 60s" >&2
          exit 1
        fi

        # Extract public key from hub's private key
        HUB_KEY=$(ssh-keygen -y -f "$SSH_KEY" 2>/dev/null)

        if [ -z "$HUB_KEY" ]; then
          echo "ERROR: Failed to read hub SSH key" >&2
          exit 1
        fi

        # Write env file if key changed
        CURRENT_KEY=""
        if [ -s "$AGENT_ENV" ]; then
          CURRENT_KEY=$(grep "^KEY=" "$AGENT_ENV" | cut -d'=' -f2-)
        fi

        if [ "$CURRENT_KEY" != "$HUB_KEY" ]; then
          echo "Updating agent environment file..."
          printf '%s\n' \
            '# Beszel agent configuration' \
            '# Auto-generated by beszel-init.service' \
            'PORT=45876' \
            "KEY=$HUB_KEY" \
            > "$AGENT_ENV"

          chown root:beszel-agent "$AGENT_ENV"
          chmod 640 "$AGENT_ENV"

          systemctl restart beszel-agent.service
        else
          echo "Agent key already up to date"
        fi
      '';
    };

    # Skip agent start until init writes the env file (first boot).
    # OnFailure notifications are independent of ordering to avoid cycles.
    systemd.services.beszel-agent = {
      unitConfig = {
        ConditionPathExists = "/var/lib/beszel-agent/env";
        OnFailure = "notify-gotify@%n.service";
      };
    };
  };
}
