version: 2.1

executors:
  nix:
    docker:
      - image: nixos/nix:latest
    environment:
      NIX_CONFIG: experimental-features = nix-command flakes

jobs:
  lint:
    executor: nix
    steps:
      - checkout
      - run:
          name: check formatting on all *.nix files
          command: |
            nix run nixpkgs#nixfmt -- --check \
              $(find . -name '*.nix' -not -path './.git/*' | sort)

  build:
    executor: nix
    steps:
      - checkout
      - run:
          name: Build
          command: nix build .#nixosConfigurations.media-server.config.system.build.toplevel

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - build
