# This file is auto-generated by nixos-generate-config on the target machine.
# Replace this placeholder with the generated config.
# See: https://nixos.wiki/wiki/NixOS_Installation_Guide
{ modulesPath, ... }: {
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.loader = {
    grub = {
      enable = true;
      devices = [ "/dev/sda" ];
    };
  };

  fileSystems."/" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };
}
