# Auto-generated by nixos-generate-config on the target machine.
# Replace boot.loader and initrd modules with the generated output.
{ modulesPath, ... }: {
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "xhci_pci"
    "ehci_pci"
  ];
}
